set udg_dhk=DialogCreate()
set udg_dqwpdhk=DialogCreate()
set gg_trg_lfhyrwbt=CreateTrigger()
call TriggerRegisterTimerEventSingle(gg_trg_lfhyrwbt,5.)
call TriggerAddAction(gg_trg_lfhyrwbt,function Trig_lfhyrwbt_Actions)
set gg_trg_lfhykqzb=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(0),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(1),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(2),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(3),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(4),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(5),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(6),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(7),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(8),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(9),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(9),"55you",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhykqzb,Player(11),"55you",true)
call TriggerAddAction(gg_trg_lfhykqzb,function Trig_lfhykqzb_Actions)
set gg_trg_lfhydtql=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(0),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(1),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(2),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(3),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(4),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(5),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(6),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(7),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(8),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(9),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(10),"quanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtql,Player(11),"quanliang",true)
call TriggerAddCondition(gg_trg_lfhydtql,Condition(function Trig_lfhydtql_Conditions))
call TriggerAddAction(gg_trg_lfhydtql,function Trig_lfhydtql_Actions)
set gg_trg_lfhydtgl=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(0),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(1),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(2),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(3),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(4),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(5),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(6),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(7),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(8),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(9),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(10),"guanquanliang",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydtgl,Player(11),"guanquanliang",true)
call TriggerAddCondition(gg_trg_lfhydtgl,Condition(function Trig_lfhydtgl_Conditions))
call TriggerAddAction(gg_trg_lfhydtgl,function Trig_lfhydtgl_Actions)
set gg_trg_lfhyjq=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(0),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(1),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(2),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(3),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(4),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(5),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(6),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(7),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(8),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(9),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(10),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjq,Player(11),"qian",false)
call TriggerAddCondition(gg_trg_lfhyjq,Condition(function Trig_lfhyjq_Conditions))
call TriggerAddAction(gg_trg_lfhyjq,function Trig_lfhyjq_Actions)
set gg_trg_lfhyjm=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(0),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(1),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(2),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(3),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(4),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(5),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(6),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(7),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(8),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(9),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(10),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjm,Player(11),"mu",false)
call TriggerAddCondition(gg_trg_lfhyjm,Condition(function Trig_lfhyjm_Conditions))
call TriggerAddAction(gg_trg_lfhyjm,function Trig_lfhyjm_Actions)
set gg_trg_lfhyjsw=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(0),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(1),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(2),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(3),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(4),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(5),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(6),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(7),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(8),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(9),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(10),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjsw,Player(11),"sanwei",false)
call TriggerAddCondition(gg_trg_lfhyjsw,Condition(function Trig_lfhyjsw_Conditions))
call TriggerAddAction(gg_trg_lfhyjsw,function Trig_lfhyjsw_Actions)
set gg_trg_lfhyjll=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(0),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(1),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(2),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(3),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(4),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(5),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(6),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(7),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(8),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(9),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(10),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjll,Player(11),"liliang",false)
call TriggerAddCondition(gg_trg_lfhyjll,Condition(function Trig_lfhyjll_Conditions))
call TriggerAddAction(gg_trg_lfhyjll,function Trig_lfhyjll_Actions)
set gg_trg_lfhyjmj=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(0),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(1),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(2),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(3),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(4),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(5),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(6),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(7),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(8),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(9),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(10),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjmj,Player(11),"minjie",false)
call TriggerAddCondition(gg_trg_lfhyjmj,Condition(function Trig_lfhyjmj_Conditions))
call TriggerAddAction(gg_trg_lfhyjmj,function Trig_lfhyjmj_Actions)
set gg_trg_lfhyjzl=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(0),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(1),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(2),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(3),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(4),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(5),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(6),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(7),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(8),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(9),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(10),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjzl,Player(11),"zhili",false)
call TriggerAddCondition(gg_trg_lfhyjzl,Condition(function Trig_lfhyjzl_Conditions))
call TriggerAddAction(gg_trg_lfhyjzl,function Trig_lfhyjzl_Actions)
set gg_trg_lfhybdjnsp=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhybdjnsp,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_lfhybdjnsp,Condition(function Trig_lfhybdjnsp_Conditions))
call TriggerAddAction(gg_trg_lfhybdjnsp,function Trig_lfhybdjnsp_Actions)
set gg_trg_lfhybdjnjf=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhybdjnjf,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_lfhybdjnjf,Condition(function Trig_lfhybdjnjf_Conditions))
call TriggerAddAction(gg_trg_lfhybdjnjf,function Trig_lfhybdjnjf_Actions)
set gg_trg_lfhybdsdxx=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhybdsdxx,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_lfhybdsdxx,Condition(function Trig_lfhybdsdxx_Conditions))
call TriggerAddAction(gg_trg_lfhybdsdxx,function Trig_lfhybdsdxx_Actions)
set gg_trg_lfhybdxlys=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhybdxlys,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_lfhybdxlys,Condition(function Trig_lfhybdxlys_Conditions))
call TriggerAddAction(gg_trg_lfhybdxlys,function Trig_lfhybdxlys_Actions)
set gg_trg_lfhybdbtxd=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhybdbtxd,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_lfhybdbtxd,Condition(function Trig_lfhybdbtxd_Conditions))
call TriggerAddAction(gg_trg_lfhybdbtxd,function Trig_lfhybdbtxd_Actions)
set gg_trg_lfhybdswjl=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhybdswjl,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_lfhybdswjl,Condition(function Trig_lfhybdswjl_Conditions))
call TriggerAddAction(gg_trg_lfhybdswjl,function Trig_lfhybdswjl_Actions)
set gg_trg_lfhydgjq=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhydgjq,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_lfhydgjq,Condition(function Trig_lfhydgjq_Conditions))
call TriggerAddAction(gg_trg_lfhydgjq,function Trig_lfhydgjq_Actions)
set gg_trg_lfhydgmt=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhydgmt,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_lfhydgmt,Condition(function Trig_lfhydgmt_Conditions))
call TriggerAddAction(gg_trg_lfhydgmt,function Trig_lfhydgmt_Actions)
set gg_trg_lfhysjewjsx=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhysjewjsx,EVENT_PLAYER_HERO_LEVEL)
call TriggerAddCondition(gg_trg_lfhysjewjsx,Condition(function Trig_lfhysjewjsx_Conditions))
call TriggerAddAction(gg_trg_lfhysjewjsx,function Trig_lfhysjewjsx_Actions)
set gg_trg_lfhyxmjm=CreateTrigger()
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(0),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(1),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(2),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(3),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(4),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(5),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(6),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(7),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(8),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(9),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(10),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyxmjm,Player(11),0,0)
call TriggerAddCondition(gg_trg_lfhyxmjm,Condition(function Trig_lfhyxmjm_Conditions))
call TriggerAddAction(gg_trg_lfhyxmjm,function Trig_lfhyxmjm_Actions)
set gg_trg_lfhyqpss=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhyqpss,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_lfhyqpss,Condition(function Trig_lfhyqpss_Conditions))
call TriggerAddAction(gg_trg_lfhyqpss,function Trig_lfhyqpss_Actions)
set gg_trg_lfhywudi=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(0),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(1),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(2),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(3),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(4),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(5),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(6),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(7),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(8),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(9),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(9),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhywudi,Player(11),"wudi",true)
call TriggerAddCondition(gg_trg_lfhywudi,Condition(function Trig_lfhywudi_Conditions))
call TriggerAddAction(gg_trg_lfhywudi,function Trig_lfhywudi_Actions)
set gg_trg_lfhyqxwd=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(0),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(1),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(2),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(3),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(4),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(5),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(6),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(7),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(8),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(9),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(9),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqxwd,Player(11),"buwudi",true)
call TriggerAddCondition(gg_trg_lfhyqxwd,Condition(function Trig_lfhyqxwd_Conditions))
call TriggerAddAction(gg_trg_lfhyqxwd,function Trig_lfhyqxwd_Actions)
set gg_trg_lfhyswjsx=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfhyswjsx,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_lfhyswjsx,Condition(function Trig_lfhyswjsx_Conditions))
call TriggerAddAction(gg_trg_lfhyswjsx,function Trig_lfhyswjsx_Actions)
set gg_trg_lfhyswjsxgb=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(0),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(1),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(2),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(3),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(4),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(5),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(6),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(7),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(8),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(9),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(10),"guanfuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxgb,Player(11),"guanfuhuo",true)
call TriggerAddCondition(gg_trg_lfhyswjsxgb,Condition(function Trig_lfhyswjsxgb_Conditions))
call TriggerAddAction(gg_trg_lfhyswjsxgb,function Trig_lfhyswjsxgb_Actions)
set gg_trg_lfhyswjsxkq=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(0),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(1),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(2),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(3),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(4),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(5),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(6),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(7),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(8),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(9),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(10),"kaifuhuo",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyswjsxkq,Player(11),"kaifuhuo",true)
call TriggerAddCondition(gg_trg_lfhyswjsxkq,Condition(function Trig_lfhyswjsxkq_Conditions))
call TriggerAddAction(gg_trg_lfhyswjsxkq,function Trig_lfhyswjsxkq_Actions)
set gg_trg_lfhyfyx=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(0),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(1),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(2),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(3),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(4),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(5),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(6),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(7),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(8),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(9),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(9),"fanyinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyfyx,Player(11),"fanyinxing",true)
call TriggerAddCondition(gg_trg_lfhyfyx,Condition(function Trig_lfhyfyx_Conditions))
call TriggerAddAction(gg_trg_lfhyfyx,function Trig_lfhyfyx_Actions)
set gg_trg_lfhyyjydsd=CreateTrigger()
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(0),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(1),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(2),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(3),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(4),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(5),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(6),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(7),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(8),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(9),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(10),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfhyyjydsd,Player(11),0,1)
call TriggerAddCondition(gg_trg_lfhyyjydsd,Condition(function Trig_lfhyyjydsd_Conditions))
call TriggerAddAction(gg_trg_lfhyyjydsd,function Trig_lfhyyjydsd_Actions)
set gg_trg_lfhybfyx=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(0),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(1),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(2),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(3),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(4),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(5),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(6),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(7),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(8),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(9),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(9),"yinxing",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhybfyx,Player(11),"yinxing",true)
call TriggerAddCondition(gg_trg_lfhybfyx,Condition(function Trig_lfhybfyx_Conditions))
call TriggerAddAction(gg_trg_lfhybfyx,function Trig_lfhybfyx_Actions)
set gg_trg_lfhyqlwp=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(0),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(1),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(2),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(3),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(4),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(5),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(6),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(7),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(8),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(9),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(9),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyqlwp,Player(11),"qingli",true)
call TriggerAddCondition(gg_trg_lfhyqlwp,Condition(function Trig_lfhyqlwp_Conditions))
call TriggerAddAction(gg_trg_lfhyqlwp,function Trig_lfhyqlwp_Actions)
set gg_trg_lfhytiren=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren2",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren3",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren4",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren5",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren6",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren7",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren8",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren9",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren10",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren11",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhytiren,Player(0),"tiren12",true)
call TriggerAddAction(gg_trg_lfhytiren,function Trig_lfhytiren_Actions)
set gg_trg_lfhyjbjy=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(0),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(1),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(2),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(3),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(4),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(5),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(6),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(7),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(8),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(9),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(10),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjbjy,Player(11),"jingyan",false)
call TriggerAddCondition(gg_trg_lfhyjbjy,Condition(function Trig_lfhyjbjy_Conditions))
call TriggerAddAction(gg_trg_lfhyjbjy,function Trig_lfhyjbjy_Actions)
set gg_trg_lfhydengji=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(0),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(1),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(2),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(3),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(4),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(5),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(6),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(7),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(8),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(9),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(10),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhydengji,Player(11),"dengji",false)
call TriggerAddCondition(gg_trg_lfhydengji,Condition(function Trig_lfhydengji_Conditions))
call TriggerAddAction(gg_trg_lfhydengji,function Trig_lfhydengji_Actions)
set gg_trg_lfhyjiangji=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(0),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(1),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(2),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(3),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(4),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(5),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(6),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(7),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(8),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(9),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(9),"jiangji",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhyjiangji,Player(11),"jiangji",true)
call TriggerAddCondition(gg_trg_lfhyjiangji,Condition(function Trig_lfhyjiangji_Conditions))
call TriggerAddAction(gg_trg_lfhyjiangji,function Trig_lfhyjiangji_Actions)
set gg_trg_lfhydhk=CreateTrigger()
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(0))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(1))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(2))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(3))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(4))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(5))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(6))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(7))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(8))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(9))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(10))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfhydhk,Player(11))
call TriggerAddCondition(gg_trg_lfhydhk,Condition(function Trig_lfhydhk_Conditions))
call TriggerAddAction(gg_trg_lfhydhk,function Trig_lfhydhk_Actions)
set gg_trg_lfhydhkfzwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydhkfzwp,udg_dhk)
call TriggerAddCondition(gg_trg_lfhydhkfzwp,Condition(function Trig_lfhydhkfzwp_Conditions))
call TriggerAddAction(gg_trg_lfhydhkfzwp,function Trig_lfhydhkfzwp_Actions)
set gg_trg_lfhywddhk=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhywddhk,udg_dhk)
call TriggerAddCondition(gg_trg_lfhywddhk,Condition(function Trig_lfhywddhk_Conditions))
call TriggerAddAction(gg_trg_lfhywddhk,function Trig_lfhywddhk_Actions)
set gg_trg_lfhyjqdhk=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhyjqdhk,udg_dhk)
call TriggerAddCondition(gg_trg_lfhyjqdhk,Condition(function Trig_lfhyjqdhk_Conditions))
call TriggerAddAction(gg_trg_lfhyjqdhk,function Trig_lfhyjqdhk_Actions)
set gg_trg_lfhyjmdhk=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhyjmdhk,udg_dhk)
call TriggerAddCondition(gg_trg_lfhyjmdhk,Condition(function Trig_lfhyjmdhk_Conditions))
call TriggerAddAction(gg_trg_lfhyjmdhk,function Trig_lfhyjmdhk_Actions)
set gg_trg_lfhyjswdhk=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhyjswdhk,udg_dhk)
call TriggerAddCondition(gg_trg_lfhyjswdhk,Condition(function Trig_lfhyjswdhk_Conditions))
call TriggerAddAction(gg_trg_lfhyjswdhk,function Trig_lfhyjswdhk_Actions)
set gg_trg_lfhyscdw=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhyscdw,udg_dhk)
call TriggerAddCondition(gg_trg_lfhyscdw,Condition(function Trig_lfhyscdw_Conditions))
call TriggerAddAction(gg_trg_lfhyscdw,function Trig_lfhyscdw_Actions)
set gg_trg_lfhydhkdj=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydhkdj,udg_dhk)
call TriggerAddCondition(gg_trg_lfhydhkdj,Condition(function Trig_lfhydhkdj_Conditions))
call TriggerAddAction(gg_trg_lfhydhkdj,function Trig_lfhydhkdj_Actions)
set gg_trg_lfhydhkqxwd=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydhkqxwd,udg_dhk)
call TriggerAddCondition(gg_trg_lfhydhkqxwd,Condition(function Trig_lfhydhkqxwd_Conditions))
call TriggerAddAction(gg_trg_lfhydhkqxwd,function Trig_lfhydhkqxwd_Actions)
set gg_trg_lfhydhkscwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydhkscwp,udg_dhk)
call TriggerAddCondition(gg_trg_lfhydhkscwp,Condition(function Trig_lfhydhkscwp_Conditions))
call TriggerAddAction(gg_trg_lfhydhkscwp,function Trig_lfhydhkscwp_Actions)
set gg_trg_lfhydhkqlwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydhkqlwp,udg_dhk)
call TriggerAddCondition(gg_trg_lfhydhkqlwp,Condition(function Trig_lfhydhkqlwp_Conditions))
call TriggerAddAction(gg_trg_lfhydhkqlwp,function Trig_lfhydhkqlwp_Actions)
set gg_trg_lfhydqdyygwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydqdyygwp,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhydqdyygwp,Condition(function Trig_lfhydqdyygwp_Conditions))
call TriggerAddAction(gg_trg_lfhydqdyygwp,function Trig_lfhydqdyygwp_Actions)
set gg_trg_lfhydqdeegwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydqdeegwp,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhydqdeegwp,Condition(function Trig_lfhydqdeegwp_Conditions))
call TriggerAddAction(gg_trg_lfhydqdeegwp,function Trig_lfhydqdeegwp_Actions)
set gg_trg_lfhydqdsasgwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydqdsasgwp,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhydqdsasgwp,Condition(function Trig_lfhydqdsasgwp_Conditions))
call TriggerAddAction(gg_trg_lfhydqdsasgwp,function Trig_lfhydqdsasgwp_Actions)
set gg_trg_lfhydqdsgwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydqdsgwp,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhydqdsgwp,Condition(function Trig_lfhydqdsgwp_Conditions))
call TriggerAddAction(gg_trg_lfhydqdsgwp,function Trig_lfhydqdsgwp_Actions)
set gg_trg_lfhydqdwgwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydqdwgwp,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhydqdwgwp,Condition(function Trig_lfhydqdwgwp_Conditions))
call TriggerAddAction(gg_trg_lfhydqdwgwp,function Trig_lfhydqdwgwp_Actions)
set gg_trg_lfhydqdlgwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydqdlgwp,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhydqdlgwp,Condition(function Trig_lfhydqdlgwp_Conditions))
call TriggerAddAction(gg_trg_lfhydqdlgwp,function Trig_lfhydqdlgwp_Actions)
set gg_trg_lfhydqsywp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydqsywp,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhydqsywp,Condition(function Trig_lfhydqsywp_Conditions))
call TriggerAddAction(gg_trg_lfhydqsywp,function Trig_lfhydqsywp_Actions)
set gg_trg_lfhytcdqdhk=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhytcdqdhk,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhytcdqdhk,Condition(function Trig_lfhytcdqdhk_Conditions))
call TriggerAddAction(gg_trg_lfhytcdqdhk,function Trig_lfhytcdqdhk_Actions)
set gg_trg_lfhydhktuihua=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhydhktuihua,udg_dhk)
call TriggerAddCondition(gg_trg_lfhydhktuihua,Condition(function Trig_lfhydhktuihua_Conditions))
call TriggerAddAction(gg_trg_lfhydhktuihua,function Trig_lfhydhktuihua_Actions)
set gg_trg_lfhyfhzqddhk=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhyfhzqddhk,udg_dqwpdhk)
call TriggerAddCondition(gg_trg_lfhyfhzqddhk,Condition(function Trig_lfhyfhzqddhk_Conditions))
call TriggerAddAction(gg_trg_lfhyfhzqddhk,function Trig_lfhyfhzqddhk_Actions)
set gg_trg_lfhytcdhk=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfhytcdhk,udg_dhk)
call TriggerAddCondition(gg_trg_lfhytcdhk,Condition(function Trig_lfhytcdhk_Conditions))
call TriggerAddAction(gg_trg_lfhytcdhk,function Trig_lfhytcdhk_Actions)