call ou99_y1d()
call FY_qwp()   
set TuanKO=0
set TuanKO=0
loop
exitwhen(TuanKO>1)
set udg_CHaoSai[TuanKO]=0
set udg_CHat[TuanKO]=""
set udg_BuernzhiA[TuanKO]=false
set udg_CHatA[TuanKO]=""
set udg_ChatB[TuanKO]=""
set udg_CHat0[TuanKO]=0
set udg_CHaojiSaiyaren[TuanKO]=""
set udg_CHaojiSaiyarenABC[TuanKO]=""
set udg_SaiYarenABC[TuanKO]=0
set udg_ABCDbu[TuanKO]=false
set udg_SHuXing[TuanKO]=0
set udg_SHiSHU[TuanKO]=0
set udg_SuiJiShu[TuanKO]=0
set udg_Xuanyunzu[TuanKO]=CreateGroup()
set udg_CHatD[TuanKO]=""
set TuanKO=TuanKO+1
endloop
set udg_SaiYaRenXiShu=22.
set gg_trg_Tuan_kaiQi=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(0),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(1),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(2),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(3),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(4),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(5),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(6),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(7),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(8),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(9),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(10),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_Tuan_kaiQi,Player(11),"",false)
call TriggerAddAction(gg_trg_Tuan_kaiQi,function Trig_Tuan_kaiQi_Actions)
set gg_trg_SaiYarenA=CreateTrigger()
call TriggerAddAction(gg_trg_SaiYarenA,function Trig_SaiYarenA_Actions)
set gg_trg_SaiYarenB=CreateTrigger()
call TriggerAddCondition(gg_trg_SaiYarenB,Condition(function Trig_SaiYarenB_Conditions))
call TriggerAddAction(gg_trg_SaiYarenB,function Trig_SaiYarenB_Actions)
set gg_trg_SaiYarenC=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_SaiYarenC,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_SaiYarenC,Condition(function Trig_SaiYarenC_Conditions))
call TriggerAddAction(gg_trg_SaiYarenC,function Trig_SaiYarenC_Actions)
set gg_trg_SaiYarenAA=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_SaiYarenAA,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerRegisterAnyUnitEventBJ(gg_trg_SaiYarenAA,EVENT_PLAYER_UNIT_SPELL_ENDCAST)
call TriggerAddCondition(gg_trg_SaiYarenAA,Condition(function Trig_SaiYarenAA_Conditions))
call TriggerAddAction(gg_trg_SaiYarenAA,function Trig_SaiYarenAA_Actions)
set gg_trg_SaiYarenBB=CreateTrigger()
call TriggerAddCondition(gg_trg_SaiYarenBB,Condition(function Trig_SaiYarenBB_Conditions))
call TriggerAddAction(gg_trg_SaiYarenBB,function Trig_SaiYarenBB_Actions)
set gg_trg_SaiYaren_BianSHen=CreateTrigger()
call TriggerAddCondition(gg_trg_SaiYaren_BianSHen,Condition(function Trig_SaiYaren_BianSHen_Conditions))
call TriggerAddAction(gg_trg_SaiYaren_BianSHen,function Trig_SaiYaren_BianSHen_Actions)
set gg_trg_SaiYaren_BianSHenJinengA1=CreateTrigger()
call DisableTrigger(gg_trg_SaiYaren_BianSHenJinengA1)
call TriggerRegisterAnyUnitEventBJ(gg_trg_SaiYaren_BianSHenJinengA1,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_SaiYaren_BianSHenJinengA1,Condition(function Trig_SaiYaren_BianSHenJinengA1_Conditions))
call TriggerAddAction(gg_trg_SaiYaren_BianSHenJinengA1,function Trig_SaiYaren_BianSHenJinengA1_Actions)
set gg_trg_SaiYaren_BianSHenJinengB2=CreateTrigger()
call DisableTrigger(gg_trg_SaiYaren_BianSHenJinengB2)
call TriggerRegisterAnyUnitEventBJ(gg_trg_SaiYaren_BianSHenJinengB2,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_SaiYaren_BianSHenJinengB2,Condition(function Trig_SaiYaren_BianSHenJinengB2_Conditions))
call TriggerAddAction(gg_trg_SaiYaren_BianSHenJinengB2,function Trig_SaiYaren_BianSHenJinengB2_Actions)
set gg_trg_SaiYaren_TuiChu=CreateTrigger()
call TriggerAddCondition(gg_trg_SaiYaren_TuiChu,Condition(function Trig_SaiYaren_TuiChu_Conditions))
call TriggerAddAction(gg_trg_SaiYaren_TuiChu,function Trig_SaiYaren_TuiChu_Actions)
set gg_trg_SaiYaren_SHuxing=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_SaiYaren_SHuxing,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_SaiYaren_SHuxing,Condition(function Trig_SaiYaren_SHuxing_Conditions))
call TriggerAddAction(gg_trg_SaiYaren_SHuxing,function Trig_SaiYaren_SHuxing_Actions)
set xwzxwz98=0
loop
exitwhen (xwzxwz98>1)
set udg_xwzxwz18[xwzxwz98]=false
set udg_xwzxwz36[xwzxwz98]=false
set udg_xwzxwz18[xwzxwz98]=false
set udg_xwzxwz31[xwzxwz98]=false
set udg_xwzxwz32[xwzxwz98]=false
set udg_xwzxwz33[xwzxwz98]=false
set udg_xwzxwz34[xwzxwz98]=false
set udg_xwzxwz35[xwzxwz98]=false
set udg_xwzxwz36[xwzxwz98]=false
set udg_xwzxwz37[xwzxwz98]=0
set udg_xwzxwz38[xwzxwz98]=0
set udg_xwzxwz39[xwzxwz98]=0
set udg_xwzxwz40[xwzxwz98]=0
set udg_xwzxwz41[xwzxwz98]=0
set udg_xwzxwz43[xwzxwz98]=false
set udg_xwzxwz47[xwzxwz98]=0
set udg_xwzxwz48[xwzxwz98]=0
set udg_xwzxwz49[xwzxwz98]=false
set udg_xwzxwz50[xwzxwz98]=0
set udg_xwzxwz51[xwzxwz98]=false
set udg_xwzxwz52[xwzxwz98]=0
set udg_xwzxwz99[xwzxwz98]=0
set udg_xwzxwz53[xwzxwz98]=false
set udg_xwzxwz100[xwzxwz98]=false
set udg_xwzxwz56[xwzxwz98]=0
set udg_xwzxwz58[xwzxwz98]=false
set udg_xwzxwz97[xwzxwz98]=false
set udg_xwzxwz70[xwzxwz98]=0
set xwzxwz98=xwzxwz98+1
endloop
set gg_trg_xwzxwz2=CreateTrigger()
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(0))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(1))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(2))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(3))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(4))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(5))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(6))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(7))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(8))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_xwzxwz2,Player(9))
call TriggerAddAction(gg_trg_xwzxwz2,function Trig_xwzxwz2_Actions)
set gg_trg_xwzxwz3=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz3)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz3,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerAddAction(gg_trg_xwzxwz3,function Trig_xwzxwz3_Actions)
set gg_trg_xwzxwz4=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz4)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz4,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerAddAction(gg_trg_xwzxwz4,function Trig_xwzxwz4_Actions)
set gg_trg_xwzxwz5=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz5)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz5,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerAddAction(gg_trg_xwzxwz5,function Trig_xwzxwz5_Actions)
set gg_trg_xwzxwz6=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz6)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_xwzxwz6,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerAddAction(gg_trg_xwzxwz6,function Trig_xwzxwz6_Actions)
set gg_trg_xwzxwz7=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz7)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(0),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(1),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(2),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(3),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(4),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(5),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(6),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(7),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(8),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(9),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz7,Player(10),true)
call TriggerAddCondition(gg_trg_xwzxwz7,Condition(function Trig_xwzxwz7_Conditions))
call TriggerAddAction(gg_trg_xwzxwz7,function Trig_xwzxwz7_Actions)
set gg_trg_xwzxwz8=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz8)
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz8,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz8,Condition(function Trig_xwzxwz8_Conditions))
call TriggerAddAction(gg_trg_xwzxwz8,function Trig_xwzxwz8_Actions)
set gg_trg_xwzxwz9=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz9)
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz9,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz9,Condition(function Trig_xwzxwz9_Conditions))
call TriggerAddAction(gg_trg_xwzxwz9,function Trig_xwzxwz9_Actions)
set gg_trg_xwzxwz10=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz10)
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz10,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz10,Condition(function Trig_xwzxwz10_Conditions))
call TriggerAddAction(gg_trg_xwzxwz10,function Trig_xwzxwz10_Actions)
set gg_trg_xwzxwz11=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz11)
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz11,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz11,Condition(function Trig_xwzxwz11_Conditions))
call TriggerAddAction(gg_trg_xwzxwz11,function Trig_xwzxwz11_Actions)
set gg_trg_xwzxwz12=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz12)
call TriggerAddAction(gg_trg_xwzxwz12,function Trig_xwzxwz12_Actions)
set gg_trg_xwzxwz13=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz13)
call TriggerAddAction(gg_trg_xwzxwz13,function Trig_xwzxwz13_Actions)
set gg_trg_xwzxwz14=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz14)
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz14,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_xwzxwz14,Condition(function Trig_xwzxwz14_Conditions))
call TriggerAddAction(gg_trg_xwzxwz14,function Trig_xwzxwz14_Actions)
set gg_trg_xwzxwz1=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz1)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(0),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(1),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(2),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(3),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(4),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(5),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(6),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(7),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(8),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1,Player(9),"removedarkweapon",true)
call TriggerAddCondition(gg_trg_xwzxwz1,Condition(function Trig_xwzxwz1_Conditions))
call TriggerAddAction(gg_trg_xwzxwz1,function Trig_xwzxwz1_Actions)
set udg_xwzxwz60=DialogCreate()
set udg_xwzxwz61=DialogCreate()
set gg_trg_xwzxwz81=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(0),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(1),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(2),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(3),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(4),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(5),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(6),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(7),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(8),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz81,Player(9),"魔道",false)
call TriggerAddCondition(gg_trg_xwzxwz81,Condition(function Trig_xwzxwz81_Conditions))
call TriggerAddAction(gg_trg_xwzxwz81,function Trig_xwzxwz81_Actions)
set gg_trg_xwzxwz82=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz82)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(0),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(1),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(2),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(3),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(4),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(5),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(6),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(7),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(8),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz82,Player(9),"进入魔道",true)
call TriggerAddCondition(gg_trg_xwzxwz82,Condition(function Trig_xwzxwz82_Conditions))
call TriggerAddAction(gg_trg_xwzxwz82,function Trig_xwzxwz82_Actions)
set gg_trg_xwzxwz83=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz83)
call TriggerAddCondition(gg_trg_xwzxwz83,Condition(function Trig_xwzxwz83_Conditions))
call TriggerAddAction(gg_trg_xwzxwz83,function Trig_xwzxwz83_Actions)
set gg_trg_xwzxwz84=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz84)
call TriggerAddAction(gg_trg_xwzxwz84,function Trig_xwzxwz84_Actions)
set gg_trg_xwzxwz84Clink=CreateTrigger()
call TriggerRegisterDialogEventBJ(gg_trg_xwzxwz84Clink,udg_xwzxwz61)
call TriggerAddAction(gg_trg_xwzxwz84Clink,function Trig_xwzxwz84Clink_Actions)
set gg_trg_xwzxwz85=CreateTrigger()
call TriggerRegisterDialogEventBJ(gg_trg_xwzxwz85,udg_xwzxwz60)
call TriggerAddAction(gg_trg_xwzxwz85,function Trig_xwzxwz85_Actions)
set gg_trg_xwzxwz1NoralPlayer=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(0),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(1),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(2),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(3),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(4),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(5),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(6),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(7),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(8),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz1NoralPlayer,Player(9),"退出魔道",true)
call TriggerAddAction(gg_trg_xwzxwz1NoralPlayer,function Trig_xwzxwz1NoralPlayer_Actions)
set gg_trg_xwzxwz86=CreateTrigger()
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(0),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(1),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(2),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(3),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(4),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(5),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(6),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(7),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(8),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_xwzxwz86,Player(9),true)
call TriggerAddCondition(gg_trg_xwzxwz86,Condition(function Trig_xwzxwz86_Conditions))
call TriggerAddAction(gg_trg_xwzxwz86,function Trig_xwzxwz86_Actions)
set gg_trg_xwzxwz87=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz87,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz87,Condition(function Trig_xwzxwz87_Conditions))
call TriggerAddAction(gg_trg_xwzxwz87,function Trig_xwzxwz87_Actions)
set gg_trg_xwzxwz87UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz87UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz87UP,Condition(function Trig_xwzxwz87UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz87UP,function Trig_xwzxwz87UP_Actions)
set gg_trg_xwzxwz88=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz88,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz88,Condition(function Trig_xwzxwz88_Conditions))
call TriggerAddAction(gg_trg_xwzxwz88,function Trig_xwzxwz88_Actions)
set gg_trg_xwzxwz88UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz88UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz88UP,Condition(function Trig_xwzxwz88UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz88UP,function Trig_xwzxwz88UP_Actions)
set gg_trg_xwzxwz89=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz89,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz89,Condition(function Trig_xwzxwz89_Conditions))
call TriggerAddAction(gg_trg_xwzxwz89,function Trig_xwzxwz89_Actions)
set gg_trg_xwzxwz89UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz89UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz89UP,Condition(function Trig_xwzxwz89UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz89UP,function Trig_xwzxwz89UP_Actions)
set gg_trg_xwzxwz90=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz90,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz90,Condition(function Trig_xwzxwz90_Conditions))
call TriggerAddAction(gg_trg_xwzxwz90,function Trig_xwzxwz90_Actions)
set gg_trg_xwzxwz90UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz90UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz90UP,Condition(function Trig_xwzxwz90UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz90UP,function Trig_xwzxwz90UP_Actions)
set gg_trg_xwzxwz91=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz91,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz91,Condition(function Trig_xwzxwz91_Conditions))
call TriggerAddAction(gg_trg_xwzxwz91,function Trig_xwzxwz91_Actions)
set gg_trg_xwzxwz91Hurt=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz91Hurt,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz91Hurt,Condition(function Trig_xwzxwz91Hurt_Conditions))
call TriggerAddAction(gg_trg_xwzxwz91Hurt,function Trig_xwzxwz91Hurt_Actions)
set gg_trg_xwzxwz91UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz91UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz91UP,Condition(function Trig_xwzxwz91UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz91UP,function Trig_xwzxwz91UP_Actions)
set gg_trg_xwzxwz92=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz92,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz92,Condition(function Trig_xwzxwz92_Conditions))
call TriggerAddAction(gg_trg_xwzxwz92,function Trig_xwzxwz92_Actions)
set gg_trg_xwzxwz92UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz92UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz92UP,Condition(function Trig_xwzxwz92UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz92UP,function Trig_xwzxwz92UP_Actions)
set gg_trg_xwzxwz9201=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz9201)
call TriggerAddAction(gg_trg_xwzxwz9201,function Trig_xwzxwz9201_Actions)
set gg_trg_xwzxwz93=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz93,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz93,Condition(function Trig_xwzxwz93_Conditions))
call TriggerAddAction(gg_trg_xwzxwz93,function Trig_xwzxwz93_Actions)
set gg_trg_xwzxwz93UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz93UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz93UP,Condition(function Trig_xwzxwz93UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz93UP,function Trig_xwzxwz93UP_Actions)
set gg_trg_xwzxwz94=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz94,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz94,Condition(function Trig_xwzxwz94_Conditions))
call TriggerAddAction(gg_trg_xwzxwz94,function Trig_xwzxwz94_Actions)
set gg_trg_xwzxwz9400=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz9400,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz9400,Condition(function Trig_xwzxwz9400_Conditions))
call TriggerAddAction(gg_trg_xwzxwz9400,function Trig_xwzxwz9400_Actions)
set gg_trg_xwzxwz94UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz94UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz94UP,Condition(function Trig_xwzxwz94UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz94UP,function Trig_xwzxwz94UP_Actions)
set gg_trg_xwzxwz95=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz95)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz95,Player(0),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz95,Player(1),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz95,Player(2),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz95,Player(3),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz95,Player(4),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz95,Player(5),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz95,Player(6),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_xwzxwz95,Player(7),"www.12349.net",true)
call TriggerAddCondition(gg_trg_xwzxwz95,Condition(function Trig_xwzxwz95_Conditions))
call TriggerAddAction(gg_trg_xwzxwz95,function Trig_xwzxwz95_Actions)
set gg_trg_xwzxwz96=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz96,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_xwzxwz96,Condition(function Trig_xwzxwz96_Conditions))
call TriggerAddAction(gg_trg_xwzxwz96,function Trig_xwzxwz96_Actions)
set gg_trg_xwzxwz97F4=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F4)
call TriggerRegisterTimerEventPeriodic(gg_trg_xwzxwz97F4,0.03)
call TriggerAddAction(gg_trg_xwzxwz97F4,function Trig_xwzxwz97F4_Actions)
set gg_trg_xwzxwz97F40=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F40)
call TriggerRegisterTimerEventPeriodic(gg_trg_xwzxwz97F40,0.60)
call TriggerAddAction(gg_trg_xwzxwz97F40,function Trig_xwzxwz97F40_Actions)
set gg_trg_xwzxwz97F16=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F16)
call TriggerRegisterTimerEventPeriodic(gg_trg_xwzxwz97F16,0.30)
call TriggerAddAction(gg_trg_xwzxwz97F16,function Trig_xwzxwz97F16_Actions)
set gg_trg_xwzxwz97F32=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F32)
call TriggerAddAction(gg_trg_xwzxwz97F32,function Trig_xwzxwz97F32_Actions)
set gg_trg_xwzxwz97F64=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F64)
call TriggerRegisterTimerEventPeriodic(gg_trg_xwzxwz97F64,0.20)
call TriggerAddAction(gg_trg_xwzxwz97F64,function Trig_xwzxwz97F64_Actions)
set gg_trg_xwzxwz97F6z16=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F6z16)
call TriggerRegisterTimerEventPeriodic(gg_trg_xwzxwz97F6z16,0.30)
call TriggerAddAction(gg_trg_xwzxwz97F6z16,function Trig_xwzxwz97F6z16_Actions)
set gg_trg_xwzxwz97F6z32=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F6z32)
call TriggerRegisterTimerEventPeriodic(gg_trg_xwzxwz97F6z32,0.20)
call TriggerAddAction(gg_trg_xwzxwz97F6z32,function Trig_xwzxwz97F6z32_Actions)
set gg_trg_xwzxwz97F6z64=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F6z64)
call TriggerRegisterTimerEventPeriodic(gg_trg_xwzxwz97F6z64,0.30)
call TriggerAddAction(gg_trg_xwzxwz97F6z64,function Trig_xwzxwz97F6z64_Actions)
set gg_trg_xwzxwz97F64death=CreateTrigger()
call DisableTrigger(gg_trg_xwzxwz97F64death)
call TriggerRegisterTimerEventPeriodic(gg_trg_xwzxwz97F64death,0.01)
call TriggerAddCondition(gg_trg_xwzxwz97F64death,Condition(function Trig_xwzxwz97F64death_Conditions))
call TriggerAddAction(gg_trg_xwzxwz97F64death,function Trig_xwzxwz97F64death_Actions)
set gg_trg_xwzxwz97Screct=CreateTrigger()
call TriggerAddCondition(gg_trg_xwzxwz97Screct,Condition(function Trig_tjzs_Conditions))
call TriggerAddAction(gg_trg_xwzxwz97Screct,function Trig_tjzs_Actions)
set gg_trg_xwzxwz96UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz96UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_xwzxwz96UP,Condition(function Trig_xwzxwz96UP_Conditions))
call TriggerAddAction(gg_trg_xwzxwz96UP,function Trig_xwzxwz96UP_Actions)
set gg_trg_xwzxwz14Normal=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_xwzxwz14Normal,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_xwzxwz14Normal,Condition(function Trig_xwzxwz14Normal_Conditions))
call TriggerAddAction(gg_trg_xwzxwz14Normal,function Trig_xwzxwz14Normal_Actions)
