set udg_xuanzedanwei=CreateGroup()
set gg_trg_cmdkqzb=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_cmdkqzb,Player(0),"hellour",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdkqzb,Player(1),"hellour",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdkqzb,Player(2),"hellour",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdkqzb,Player(3),"hellour",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdkqzb,Player(4),"hellour",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdkqzb,Player(5),"hellour",true)
call TriggerAddAction(gg_trg_cmdkqzb,function Trig_kqzb_Actions)
set gg_trg_cmdwudi=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_cmdwudi,Player(0),"开启无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdwudi,Player(1),"开启无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdwudi,Player(2),"开启无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdwudi,Player(3),"开启无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdwudi,Player(4),"开启无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdwudi,Player(5),"开启无敌",true)
call TriggerAddCondition(gg_trg_cmdwudi,Condition(function Trig_cmdwudi_Conditions))
call TriggerAddAction(gg_trg_cmdwudi,function Trig_cmdwudi_Actions) 
set gg_trg_cmdbuwudi=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_cmdbuwudi,Player(0),"关闭无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdbuwudi,Player(1),"关闭无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdbuwudi,Player(2),"关闭无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdbuwudi,Player(3),"关闭无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdbuwudi,Player(4),"关闭无敌",true)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdbuwudi,Player(5),"关闭无敌",true)
call TriggerAddCondition(gg_trg_cmdbuwudi,Condition(function Trig_cmdbuwudi_Conditions))
call TriggerAddAction(gg_trg_cmdbuwudi,function Trig_cmdbuwudi_Actions)
set gg_trg_cmdtssw=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_cmdtssw,Player(0),"天外飞仙",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdtssw,Player(1),"天外飞仙",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdtssw,Player(2),"天外飞仙",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdtssw,Player(3),"天外飞仙",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdtssw,Player(4),"天外飞仙",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdtssw,Player(5),"天外飞仙",false)
call TriggerAddCondition(gg_trg_cmdtssw,Condition(function Trig_cmdtssw_Conditions))
call TriggerAddAction(gg_trg_cmdtssw,function Trig_cmdtssw_Actions)
set gg_trg_cmdjssw=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_cmdjssw,Player(0),"坠落凡尘",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdjssw,Player(1),"坠落凡尘",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdjssw,Player(2),"坠落凡尘",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdjssw,Player(3),"坠落凡尘",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdjssw,Player(4),"坠落凡尘",false)
call TriggerRegisterPlayerChatEvent(gg_trg_cmdjssw,Player(5),"坠落凡尘",false)
call TriggerAddCondition(gg_trg_cmdjssw,Condition(function Trig_cmdjssw_Conditions))
call TriggerAddAction(gg_trg_cmdjssw,function Trig_cmdjssw_Actions)