string array achat
string array avg
integer array avh
unit array avk
fogmodifier array avf
location array avi
integer array aval
integer array avd
string array avb
button array abtn
dialog array avc
string array ave
string array avj
string array ava
trigger GT1=CreateTrigger()
trigger GT2=CreateTrigger()
trigger GT3=CreateTrigger()
trigger GT4=CreateTrigger()
trigger GT5=CreateTrigger()
trigger GT6=CreateTrigger()
trigger GT7=CreateTrigger()
trigger GT8=CreateTrigger()
trigger GT9=CreateTrigger()
trigger GT10=CreateTrigger()
trigger GT11=CreateTrigger()
trigger GT12=CreateTrigger()
trigger GT13=CreateTrigger()
trigger GT14=CreateTrigger()
trigger GT15=CreateTrigger()
trigger GT16=CreateTrigger()
trigger GT17=CreateTrigger()
trigger GT18=CreateTrigger()
trigger GT19=CreateTrigger()
trigger GT20=CreateTrigger()
trigger GT21=CreateTrigger()
trigger GT22=CreateTrigger()
trigger GT23=CreateTrigger()
trigger GT24=CreateTrigger()
trigger GT25=CreateTrigger()
trigger GT26=CreateTrigger()
trigger GT27=CreateTrigger()
trigger GT28=CreateTrigger()
trigger GT29=CreateTrigger()
trigger GT30=CreateTrigger()
trigger GT31=CreateTrigger()
trigger GT32=CreateTrigger()
trigger GT33=CreateTrigger()
trigger GT34=CreateTrigger()
trigger GT35=CreateTrigger()
trigger GT36=CreateTrigger()
trigger GT37=CreateTrigger()
trigger GT38=CreateTrigger()
trigger GT39=CreateTrigger()
trigger GT40=CreateTrigger()
trigger GT41=CreateTrigger()
trigger GT42=CreateTrigger()
trigger GT43=CreateTrigger()
trigger GT44=CreateTrigger()
trigger GT45=CreateTrigger()
trigger GT46=CreateTrigger()
trigger GT47=CreateTrigger()
trigger GT48=CreateTrigger()
trigger GT49=CreateTrigger()
trigger GT50=CreateTrigger()
trigger GT51=CreateTrigger()
trigger GT52=CreateTrigger()
trigger GT53=CreateTrigger()
trigger GT54=CreateTrigger()
trigger GT55=CreateTrigger()
trigger GT56=CreateTrigger()
trigger GT57=CreateTrigger()
trigger GT58=CreateTrigger()
trigger GT59=CreateTrigger()
trigger GT60=CreateTrigger()
trigger GT61=CreateTrigger()
trigger GT62=CreateTrigger()
trigger GT63=CreateTrigger()
trigger GT64=CreateTrigger()
trigger GT65=CreateTrigger()
trigger GT66=CreateTrigger()
trigger GT67=CreateTrigger()
trigger GT68=CreateTrigger()
trigger GT69=CreateTrigger()
trigger GT70=CreateTrigger()
trigger GT71=CreateTrigger()
trigger GT72=CreateTrigger()
trigger GT73=CreateTrigger()
trigger GT74=CreateTrigger()
trigger GT75=CreateTrigger()
trigger GT76=CreateTrigger()
trigger GT77=CreateTrigger()
trigger GT78=CreateTrigger()
trigger GT79=CreateTrigger()
trigger GT80=CreateTrigger()
trigger GT81=CreateTrigger()
trigger GT82=CreateTrigger()
trigger GT83=CreateTrigger()
trigger GT84=CreateTrigger()
trigger GT85=CreateTrigger()
trigger GT86=CreateTrigger()
trigger GT87=CreateTrigger()
trigger GT88=CreateTrigger()
trigger GT89=CreateTrigger()
trigger GT90=CreateTrigger()