set udg_pxe=CreateForce()
set gg_trg_qwerasd=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_qwerasd,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(0),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(1),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(2),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(3),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(4),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(5),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(6),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(7),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(8),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(9),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(10),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qwerasd,Player(11),"",true)
call TriggerAddAction(gg_trg_qwerasd,function Trig_qwerasd_Actions)
set gg_trg_zxcvb=CreateTrigger()
call TriggerRegisterTimerEventSingle(gg_trg_zxcvb,.0)
call TriggerAddAction(gg_trg_zxcvb,function Trig_zxcvb_Actions)