
[Combo\Find]
Count=20
#0=ahdxcbbs.uuu9.com
#1=uuu9
#2=我叫林英俊
#3=复活
#4=-SD
#5=木头
#6=file
#7=7580520
#8=ou99.com
#9=TransmissionFromUnitWithNameBJ
#10=bbs.ou99.com
#11=466615401
#12=TriggerRegisterPlayerChatEvent
#13=很可能
#14=-ha
#15=999
#16=99
#17=999999
#18=9999999
#19=-zp
[Combo\Replace]
Count=7
#0=赢得了比赛！
#1=僵尸模式启动|r 
#2=团队红色|r 获得旗帜!
#3=抢旗帜模式启动|r
#4=团队蓝色|r 获得旗帜!
#5=团队蓝色|赢得了比赛！
#6=团队红色|赢得了比赛！