call mhhke_z09Z()
call InitTrig_hc()
call InitTrig_feiba()
call InitTrig_guanbifeiba()
call InitTrig_WCD()
set gg_trg_yedfsadgsdg=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(0),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(1),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(2),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(3),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(4),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(5),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(6),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(7),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(8),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(9),"",true)
call TriggerAddCondition(gg_trg_yedfsadgsdg,Condition(function Trig_yedfsadgsdg_Conditions))
call TriggerAddAction(gg_trg_yedfsadgsdg,function Trig_yedfsadgsdg_Actions)
call InitTrig_jaffc()
call InitTrig_jaffc1()
call InitTrig_BigMan()
set gg_trg_qqqq=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(0),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(1),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(2),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(3),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(4),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(5),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(6),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(7),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(8),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(9),"",true)
call TriggerAddCondition(gg_trg_qqqq,Condition(function Trig_qqqq_Conditions))
call TriggerAddAction(gg_trg_qqqq,function Trig_qqqq_Actions)
call SDMJ()
set gg_trg_Fire=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_Fire,Player(0),"诸神领域-红",true)
call TriggerAddAction(gg_trg_Fire,function Trig_Fire_Actions)
set gg_trg_Fire1=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_Fire1,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Fire1,Condition(function Trig_Fire1_Conditions))
call TriggerAddAction(gg_trg_Fire1,function Trig_Fire1_Actions)
set gg_trg_Fire2=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Fire2,Player(0),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Fire2,Condition(function Trig_Fire2_Conditions))
call TriggerAddAction(gg_trg_Fire2,function Trig_Fire2_Actions)
set gg_trg_Fire3=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Fire3,Player(0),EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_Fire3,Condition(function Trig_Fire3_Conditions))
call TriggerAddAction(gg_trg_Fire3,function Trig_Fire3_Actions)
set gg_trg_Fire4=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Fire4,Player(0),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Fire4,Condition(function Trig_Fire4_Conditions))
call TriggerAddAction(gg_trg_Fire4,function Trig_Fire4_Actions)
set gg_trg_Ice=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_Ice,Player(1),"诸神领域-蓝",true)
call TriggerAddAction(gg_trg_Ice,function Trig_Ice_Actions)
set gg_trg_Ice1=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_Ice1,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Ice1,Condition(function Trig_Ice1_Conditions))
call TriggerAddAction(gg_trg_Ice1,function Trig_Ice1_Actions)
set gg_trg_Ice2=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Ice2,Player(1),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Ice2,Condition(function Trig_Ice2_Conditions))
call TriggerAddAction(gg_trg_Ice2,function Trig_Ice2_Actions)
set gg_trg_Ice3=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Ice3,Player(1),EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_Ice3,Condition(function Trig_Ice3_Conditions))
call TriggerAddAction(gg_trg_Ice3,function Trig_Ice3_Actions)
set gg_trg_Ice4=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Ice4,Player(1),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Ice4,Condition(function Trig_Ice4_Conditions))
call TriggerAddAction(gg_trg_Ice4,function Trig_Ice4_Actions)
set gg_trg_Bolt=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_Bolt,Player(2),"诸神领域-青",true)
call TriggerAddAction(gg_trg_Bolt,function Trig_Bolt_Actions)
set gg_trg_Bolt1=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_Bolt1,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Bolt1,Condition(function Trig_Bolt1_Conditions))
call TriggerAddAction(gg_trg_Bolt1,function Trig_Bolt1_Actions)
set gg_trg_Bolt2=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Bolt2,Player(2),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Bolt2,Condition(function Trig_Bolt2_Conditions))
call TriggerAddAction(gg_trg_Bolt2,function Trig_Bolt2_Actions)
set gg_trg_Bolt3=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Bolt3,Player(2),EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_Bolt3,Condition(function Trig_Bolt3_Conditions))
call TriggerAddAction(gg_trg_Bolt3,function Trig_Bolt3_Actions)
set gg_trg_Bolt4=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Bolt4,Player(2),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Bolt4,Condition(function Trig_Bolt4_Conditions))
call TriggerAddAction(gg_trg_Bolt4,function Trig_Bolt4_Actions)
set gg_trg_Moon=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_Moon,Player(3),"诸神领域-紫",true)
call TriggerAddAction(gg_trg_Moon,function Trig_Moon_Actions)
set gg_trg_Moon1=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_Moon1,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Moon1,Condition(function Trig_Moon1_Conditions))
call TriggerAddAction(gg_trg_Moon1,function Trig_Moon1_Actions)
set gg_trg_Moon2=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Moon2,Player(3),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Moon2,Condition(function Trig_Moon2_Conditions))
call TriggerAddAction(gg_trg_Moon2,function Trig_Moon2_Actions)
set gg_trg_Moon3=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Moon3,Player(3),EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_Moon3,Condition(function Trig_Moon3_Conditions))
call TriggerAddAction(gg_trg_Moon3,function Trig_Moon3_Actions)
set gg_trg_Moon4=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Moon4,Player(3),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Moon4,Condition(function Trig_Moon4_Conditions))
call TriggerAddAction(gg_trg_Moon4,function Trig_Moon4_Actions)
set gg_trg_Light=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_Light,Player(4),"诸神领域-黄",true)
call TriggerAddAction(gg_trg_Light,function Trig_Light_Actions)
set gg_trg_Light1=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_Light1,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Light1,Condition(function Trig_Light1_Conditions))
call TriggerAddAction(gg_trg_Light1,function Trig_Light1_Actions)
set gg_trg_Light2=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Light2,Player(4),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Light2,Condition(function Trig_Light2_Conditions))
call TriggerAddAction(gg_trg_Light2,function Trig_Light2_Actions)
set gg_trg_Light3=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Light3,Player(4),EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_Light3,Condition(function Trig_Light3_Conditions))
call TriggerAddAction(gg_trg_Light3,function Trig_Light3_Actions)
set gg_trg_Light4=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Light4,Player(4),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Light4,Condition(function Trig_Light4_Conditions))
call TriggerAddAction(gg_trg_Light4,function Trig_Light4_Actions)
set gg_trg_Wind=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_Wind,Player(5),"诸神领域-橙",true)
call TriggerAddAction(gg_trg_Wind,function Trig_Wind_Actions)
set gg_trg_Wind1=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_Wind1,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Wind1,Condition(function Trig_Wind1_Conditions))
call TriggerAddAction(gg_trg_Wind1,function Trig_Wind1_Actions)
set gg_trg_Wind2=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Wind2,Player(5),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Wind2,Condition(function Trig_Wind2_Conditions))
call TriggerAddAction(gg_trg_Wind2,function Trig_Wind2_Actions)
set gg_trg_Wind3=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Wind3,Player(5),EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_Wind3,Condition(function Trig_Wind3_Conditions))
call TriggerAddAction(gg_trg_Wind3,function Trig_Wind3_Actions)
set gg_trg_Wind4=CreateTrigger()
call TriggerRegisterPlayerUnitEventSimple(gg_trg_Wind4,Player(5),EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_Wind4,Condition(function Trig_Wind4_Conditions))
call TriggerAddAction(gg_trg_Wind4,function Trig_Wind4_Actions)
call Wu_Jie_Bian_Huan_1()
call Wu_Jie_Bian_Huan_2()
call Wu_Jie_Bian_Huan_3()
call FY_qwp()
call ljzc()
set liuboi=0
set udg_zliuboz=CreateForce()
set liuboi=0
loop
exitwhen(liuboi>1)
set udg_cliuboc[liuboi]=0
set udg_itp[liuboi]=0
set udg_itpp[liuboi]=0
set liuboi=liuboi+1
endloop
set gg_trg_erfsfd=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(0),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(1),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(2),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(3),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(4),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(5),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(6),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(7),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(8),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_erfsfd,Player(9),"",true)
call TriggerAddAction(gg_trg_erfsfd,function Trig_erfsfd_Actions)
set gg_trg_sdfaw=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_sdfaw,EVENT_PLAYER_UNIT_PICKUP_ITEM)
call TriggerAddAction(gg_trg_sdfaw,function Trig_sdfaw_Actions)
set gg_trg_sdqwaa=CreateTrigger()
call TriggerRegisterTimerEventSingle(gg_trg_sdqwaa,.1)
call TriggerAddAction(gg_trg_sdqwaa,function Trig_sdqwaa_Actions)
set gg_trg_sdqasdf=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_sdqasdf,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddAction(gg_trg_sdqasdf,function Trig_sdqasdf_Actions)
set gg_trg_sdeewew=CreateTrigger()
call TriggerRegisterTimerEventPeriodic(gg_trg_sdeewew,60.)
call TriggerAddAction(gg_trg_sdeewew,function Trig_sdeewew_Actions)
set mhmdjb98=0
loop
exitwhen (mhmdjb98>1)
set udg_mhmdjb18[mhmdjb98]=false
set udg_mhmdjb36[mhmdjb98]=false
set udg_mhmdjb18[mhmdjb98]=false
set udg_mhmdjb31[mhmdjb98]=false
set udg_mhmdjb32[mhmdjb98]=false
set udg_mhmdjb33[mhmdjb98]=false
set udg_mhmdjb34[mhmdjb98]=false
set udg_mhmdjb35[mhmdjb98]=false
set udg_mhmdjb36[mhmdjb98]=false
set udg_mhmdjb37[mhmdjb98]=0
set udg_mhmdjb38[mhmdjb98]=0
set udg_mhmdjb39[mhmdjb98]=0
set udg_mhmdjb40[mhmdjb98]=0
set udg_mhmdjb41[mhmdjb98]=0
set udg_mhmdjb43[mhmdjb98]=false
set udg_mhmdjb47[mhmdjb98]=0
set udg_mhmdjb48[mhmdjb98]=0
set udg_mhmdjb49[mhmdjb98]=false
set udg_mhmdjb50[mhmdjb98]=0
set udg_mhmdjb51[mhmdjb98]=false
set udg_mhmdjb52[mhmdjb98]=0
set udg_mhmdjb99[mhmdjb98]=0
set udg_mhmdjb53[mhmdjb98]=false
set udg_mhmdjb100[mhmdjb98]=false
set udg_mhmdjb56[mhmdjb98]=0
set udg_mhmdjb58[mhmdjb98]=false
set udg_mhmdjb97[mhmdjb98]=false
set udg_mhmdjb70[mhmdjb98]=0
set mhmdjb98=mhmdjb98+1
endloop
set gg_trg_mhmdjb2=CreateTrigger()
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(0))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(1))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(2))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(3))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(4))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(5))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(6))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(7))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(8))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_mhmdjb2,Player(9))
call TriggerAddAction(gg_trg_mhmdjb2,function Trig_mhmdjb2_Actions)
set gg_trg_mhmdjb3=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb3)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb3,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerAddAction(gg_trg_mhmdjb3,function Trig_mhmdjb3_Actions)
set gg_trg_mhmdjb4=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb4)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb4,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerAddAction(gg_trg_mhmdjb4,function Trig_mhmdjb4_Actions)
set gg_trg_mhmdjb5=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb5)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb5,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerAddAction(gg_trg_mhmdjb5,function Trig_mhmdjb5_Actions)
set gg_trg_mhmdjb6=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb6)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_mhmdjb6,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerAddAction(gg_trg_mhmdjb6,function Trig_mhmdjb6_Actions)
set gg_trg_mhmdjb7=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb7)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(0),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(1),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(2),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(3),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(4),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(5),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(6),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(7),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(8),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(9),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb7,Player(10),true)
call TriggerAddCondition(gg_trg_mhmdjb7,Condition(function Trig_mhmdjb7_Conditions))
call TriggerAddAction(gg_trg_mhmdjb7,function Trig_mhmdjb7_Actions)
set gg_trg_mhmdjb8=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb8)
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb8,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb8,Condition(function Trig_mhmdjb8_Conditions))
call TriggerAddAction(gg_trg_mhmdjb8,function Trig_mhmdjb8_Actions)
set gg_trg_mhmdjb9=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb9)
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb9,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb9,Condition(function Trig_mhmdjb9_Conditions))
call TriggerAddAction(gg_trg_mhmdjb9,function Trig_mhmdjb9_Actions)
set gg_trg_mhmdjb10=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb10)
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb10,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb10,Condition(function Trig_mhmdjb10_Conditions))
call TriggerAddAction(gg_trg_mhmdjb10,function Trig_mhmdjb10_Actions)
set gg_trg_mhmdjb11=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb11)
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb11,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb11,Condition(function Trig_mhmdjb11_Conditions))
call TriggerAddAction(gg_trg_mhmdjb11,function Trig_mhmdjb11_Actions)
set gg_trg_mhmdjb12=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb12)
call TriggerAddAction(gg_trg_mhmdjb12,function Trig_mhmdjb12_Actions)
set gg_trg_mhmdjb13=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb13)
call TriggerAddAction(gg_trg_mhmdjb13,function Trig_mhmdjb13_Actions)
set gg_trg_mhmdjb14=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb14)
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb14,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_mhmdjb14,Condition(function Trig_mhmdjb14_Conditions))
call TriggerAddAction(gg_trg_mhmdjb14,function Trig_mhmdjb14_Actions)
set gg_trg_mhmdjb1=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb1)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(0),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(1),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(2),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(3),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(4),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(5),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(6),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(7),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(8),"removedarkweapon",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1,Player(9),"removedarkweapon",true)
call TriggerAddCondition(gg_trg_mhmdjb1,Condition(function Trig_mhmdjb1_Conditions))
call TriggerAddAction(gg_trg_mhmdjb1,function Trig_mhmdjb1_Actions)
set udg_mhmdjb60=DialogCreate()
set udg_mhmdjb61=DialogCreate()
set gg_trg_mhmdjb81=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(0),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(1),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(2),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(3),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(4),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(5),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(6),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(7),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(8),"魔道",false)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb81,Player(9),"魔道",false)
call TriggerAddCondition(gg_trg_mhmdjb81,Condition(function Trig_mhmdjb81_Conditions))
call TriggerAddAction(gg_trg_mhmdjb81,function Trig_mhmdjb81_Actions)
set gg_trg_mhmdjb82=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb82)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(0),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(1),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(2),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(3),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(4),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(5),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(6),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(7),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(8),"进入魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb82,Player(9),"进入魔道",true)
call TriggerAddCondition(gg_trg_mhmdjb82,Condition(function Trig_mhmdjb82_Conditions))
call TriggerAddAction(gg_trg_mhmdjb82,function Trig_mhmdjb82_Actions)
set gg_trg_mhmdjb83=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb83)
call TriggerAddCondition(gg_trg_mhmdjb83,Condition(function Trig_mhmdjb83_Conditions))
call TriggerAddAction(gg_trg_mhmdjb83,function Trig_mhmdjb83_Actions)
set gg_trg_mhmdjb84=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb84)
call TriggerAddAction(gg_trg_mhmdjb84,function Trig_mhmdjb84_Actions)
set gg_trg_mhmdjb84Clink=CreateTrigger()
call TriggerRegisterDialogEventBJ(gg_trg_mhmdjb84Clink,udg_mhmdjb61)
call TriggerAddAction(gg_trg_mhmdjb84Clink,function Trig_mhmdjb84Clink_Actions)
set gg_trg_mhmdjb85=CreateTrigger()
call TriggerRegisterDialogEventBJ(gg_trg_mhmdjb85,udg_mhmdjb60)
call TriggerAddAction(gg_trg_mhmdjb85,function Trig_mhmdjb85_Actions)
set gg_trg_mhmdjb1NoralPlayer=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(0),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(1),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(2),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(3),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(4),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(5),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(6),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(7),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(8),"退出魔道",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb1NoralPlayer,Player(9),"退出魔道",true)
call TriggerAddAction(gg_trg_mhmdjb1NoralPlayer,function Trig_mhmdjb1NoralPlayer_Actions)
set gg_trg_mhmdjb86=CreateTrigger()
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(0),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(1),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(2),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(3),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(4),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(5),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(6),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(7),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(8),true)
call TriggerRegisterPlayerSelectionEventBJ(gg_trg_mhmdjb86,Player(9),true)
call TriggerAddCondition(gg_trg_mhmdjb86,Condition(function Trig_mhmdjb86_Conditions))
call TriggerAddAction(gg_trg_mhmdjb86,function Trig_mhmdjb86_Actions)
set gg_trg_mhmdjb87=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb87,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb87,Condition(function Trig_mhmdjb87_Conditions))
call TriggerAddAction(gg_trg_mhmdjb87,function Trig_mhmdjb87_Actions)
set gg_trg_mhmdjb87UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb87UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb87UP,Condition(function Trig_mhmdjb87UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb87UP,function Trig_mhmdjb87UP_Actions)
set gg_trg_mhmdjb88=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb88,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb88,Condition(function Trig_mhmdjb88_Conditions))
call TriggerAddAction(gg_trg_mhmdjb88,function Trig_mhmdjb88_Actions)
set gg_trg_mhmdjb88UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb88UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb88UP,Condition(function Trig_mhmdjb88UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb88UP,function Trig_mhmdjb88UP_Actions)
set gg_trg_mhmdjb89=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb89,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb89,Condition(function Trig_mhmdjb89_Conditions))
call TriggerAddAction(gg_trg_mhmdjb89,function Trig_mhmdjb89_Actions)
set gg_trg_mhmdjb89UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb89UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb89UP,Condition(function Trig_mhmdjb89UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb89UP,function Trig_mhmdjb89UP_Actions)
set gg_trg_mhmdjb90=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb90,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb90,Condition(function Trig_mhmdjb90_Conditions))
call TriggerAddAction(gg_trg_mhmdjb90,function Trig_mhmdjb90_Actions)
set gg_trg_mhmdjb90UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb90UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb90UP,Condition(function Trig_mhmdjb90UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb90UP,function Trig_mhmdjb90UP_Actions)
set gg_trg_mhmdjb91=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb91,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb91,Condition(function Trig_mhmdjb91_Conditions))
call TriggerAddAction(gg_trg_mhmdjb91,function Trig_mhmdjb91_Actions)
set gg_trg_mhmdjb91Hurt=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb91Hurt,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb91Hurt,Condition(function Trig_mhmdjb91Hurt_Conditions))
call TriggerAddAction(gg_trg_mhmdjb91Hurt,function Trig_mhmdjb91Hurt_Actions)
set gg_trg_mhmdjb91UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb91UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb91UP,Condition(function Trig_mhmdjb91UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb91UP,function Trig_mhmdjb91UP_Actions)
set gg_trg_mhmdjb92=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb92,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb92,Condition(function Trig_mhmdjb92_Conditions))
call TriggerAddAction(gg_trg_mhmdjb92,function Trig_mhmdjb92_Actions)
set gg_trg_mhmdjb92UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb92UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb92UP,Condition(function Trig_mhmdjb92UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb92UP,function Trig_mhmdjb92UP_Actions)
set gg_trg_mhmdjb9201=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb9201)
call TriggerAddAction(gg_trg_mhmdjb9201,function Trig_mhmdjb9201_Actions)
set gg_trg_mhmdjb93=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb93,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb93,Condition(function Trig_mhmdjb93_Conditions))
call TriggerAddAction(gg_trg_mhmdjb93,function Trig_mhmdjb93_Actions)
set gg_trg_mhmdjb93UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb93UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb93UP,Condition(function Trig_mhmdjb93UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb93UP,function Trig_mhmdjb93UP_Actions)
set gg_trg_mhmdjb94=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb94,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb94,Condition(function Trig_mhmdjb94_Conditions))
call TriggerAddAction(gg_trg_mhmdjb94,function Trig_mhmdjb94_Actions)
set gg_trg_mhmdjb9400=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb9400,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb9400,Condition(function Trig_mhmdjb9400_Conditions))
call TriggerAddAction(gg_trg_mhmdjb9400,function Trig_mhmdjb9400_Actions)
set gg_trg_mhmdjb94UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb94UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb94UP,Condition(function Trig_mhmdjb94UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb94UP,function Trig_mhmdjb94UP_Actions)
set gg_trg_mhmdjb95=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb95)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb95,Player(0),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb95,Player(1),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb95,Player(2),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb95,Player(3),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb95,Player(4),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb95,Player(5),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb95,Player(6),"www.12349.net",true)
call TriggerRegisterPlayerChatEvent(gg_trg_mhmdjb95,Player(7),"www.12349.net",true)
call TriggerAddCondition(gg_trg_mhmdjb95,Condition(function Trig_mhmdjb95_Conditions))
call TriggerAddAction(gg_trg_mhmdjb95,function Trig_mhmdjb95_Actions)
set gg_trg_mhmdjb96=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb96,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_mhmdjb96,Condition(function Trig_mhmdjb96_Conditions))
call TriggerAddAction(gg_trg_mhmdjb96,function Trig_mhmdjb96_Actions)
set gg_trg_mhmdjb97F4=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F4)
call TriggerRegisterTimerEventPeriodic(gg_trg_mhmdjb97F4,0.03)
call TriggerAddAction(gg_trg_mhmdjb97F4,function Trig_mhmdjb97F4_Actions)
set gg_trg_mhmdjb97F40=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F40)
call TriggerRegisterTimerEventPeriodic(gg_trg_mhmdjb97F40,0.60)
call TriggerAddAction(gg_trg_mhmdjb97F40,function Trig_mhmdjb97F40_Actions)
set gg_trg_mhmdjb97F16=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F16)
call TriggerRegisterTimerEventPeriodic(gg_trg_mhmdjb97F16,0.30)
call TriggerAddAction(gg_trg_mhmdjb97F16,function Trig_mhmdjb97F16_Actions)
set gg_trg_mhmdjb97F32=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F32)
call TriggerAddAction(gg_trg_mhmdjb97F32,function Trig_mhmdjb97F32_Actions)
set gg_trg_mhmdjb97F64=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F64)
call TriggerRegisterTimerEventPeriodic(gg_trg_mhmdjb97F64,0.20)
call TriggerAddAction(gg_trg_mhmdjb97F64,function Trig_mhmdjb97F64_Actions)
set gg_trg_mhmdjb97F6z16=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F6z16)
call TriggerRegisterTimerEventPeriodic(gg_trg_mhmdjb97F6z16,0.30)
call TriggerAddAction(gg_trg_mhmdjb97F6z16,function Trig_mhmdjb97F6z16_Actions)
set gg_trg_mhmdjb97F6z32=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F6z32)
call TriggerRegisterTimerEventPeriodic(gg_trg_mhmdjb97F6z32,0.20)
call TriggerAddAction(gg_trg_mhmdjb97F6z32,function Trig_mhmdjb97F6z32_Actions)
set gg_trg_mhmdjb97F6z64=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F6z64)
call TriggerRegisterTimerEventPeriodic(gg_trg_mhmdjb97F6z64,0.30)
call TriggerAddAction(gg_trg_mhmdjb97F6z64,function Trig_mhmdjb97F6z64_Actions)
set gg_trg_mhmdjb97F64death=CreateTrigger()
call DisableTrigger(gg_trg_mhmdjb97F64death)
call TriggerRegisterTimerEventPeriodic(gg_trg_mhmdjb97F64death,0.01)
call TriggerAddCondition(gg_trg_mhmdjb97F64death,Condition(function Trig_mhmdjb97F64death_Conditions))
call TriggerAddAction(gg_trg_mhmdjb97F64death,function Trig_mhmdjb97F64death_Actions)
set gg_trg_mhmdjb97Screct=CreateTrigger()
call TriggerAddCondition(gg_trg_mhmdjb97Screct,Condition(function Trig_tjzs_Conditions))
call TriggerAddAction(gg_trg_mhmdjb97Screct,function Trig_tjzs_Actions)
set gg_trg_mhmdjb96UP=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb96UP,EVENT_PLAYER_UNIT_DEATH)
call TriggerAddCondition(gg_trg_mhmdjb96UP,Condition(function Trig_mhmdjb96UP_Conditions))
call TriggerAddAction(gg_trg_mhmdjb96UP,function Trig_mhmdjb96UP_Actions)
set gg_trg_mhmdjb14Normal=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_mhmdjb14Normal,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_mhmdjb14Normal,Condition(function Trig_mhmdjb14Normal_Conditions))
call TriggerAddAction(gg_trg_mhmdjb14Normal,function Trig_mhmdjb14Normal_Actions)