set zfs_sz=0
loop
exitwhen(zfs_sz>100)
set zfs_e[zfs_sz]=0
set zfs_sz=zfs_sz+1
endloop
set zfs_sz=0
loop
exitwhen(zfs_sz>100)
set zfs_x[zfs_sz]=0
set zfs_sz=zfs_sz+1
endloop
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(0))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(1))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(2))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(3))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(4))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(5))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(6))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(7))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(8))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(9))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(10))
call TriggerRegisterPlayerEventEndCinematic(zfs_r,Player(11))
call TriggerRegisterAnyUnitEventBJ(zfs_A,EVENT_PLAYER_UNIT_SPELL_CAST)
call TriggerRegisterAnyUnitEventBJ(zfs_c,EVENT_PLAYER_UNIT_PICKUP_ITEM)
call TriggerRegisterAnyUnitEventBJ(zfs_c,EVENT_PLAYER_UNIT_DROP_ITEM)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(10),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_d,Player(11),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_UP)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(10),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_D,Player(11),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_LEFT)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(10),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_f,Player(11),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_DOWN)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(0),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(1),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(2),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(3),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(4),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(5),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(6),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(7),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(8),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(9),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(10),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerRegisterPlayerKeyEventBJ(zfs_F,Player(11),bj_KEYEVENTTYPE_DEPRESS,bj_KEYEVENTKEY_RIGHT)
call TriggerAddAction(zfs_r,function zfs_z)
call TriggerAddAction(zfs_V,function zfs_vv)
call TriggerAddAction(zfs_E,function zfs_xv)
call TriggerAddAction(zfs_X,function zfs_rv)
call TriggerAddAction(zfs_O,function zfs_nv)
call TriggerAddAction(zfs_R,function zfs_Xv)
call TriggerAddAction(zfs_A,function zfs_Rv)
call TriggerAddAction(zfs_N,function zfs_Av)
call TriggerAddAction(zfs_B,function zfs_bv)
call TriggerAddAction(zfs_c,function zfs_cv)
call TriggerAddAction(zfs_C,function zfs_dv)
call TriggerAddAction(zfs_d,function zfs_gv)
call TriggerAddAction(zfs_D,function zfs_kv)
call TriggerAddAction(zfs_f,function zfs_mv)
call TriggerAddAction(zfs_F,function zfs_qv)
call TriggerAddCondition(zfs_V,Condition(function zfs_y))
call TriggerAddCondition(zfs_E,Condition(function zfs_y))
call TriggerAddCondition(zfs_O,Condition(function zfs_av))
call TriggerAddCondition(zfs_R,Condition(function zfs_Ev))
call TriggerAddCondition(zfs_A,Condition(function zfs_y))
call TriggerAddCondition(zfs_N,Condition(function zfs_y))
call TriggerAddCondition(zfs_B,Condition(function zfs_y))
call TriggerAddCondition(zfs_c,Condition(function zfs_y))
call TriggerAddCondition(zfs_C,Condition(function zfs_y))
