set gg_trg_qqqq=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(0),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(1),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(2),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(3),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(4),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(5),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(6),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_qqqq,Player(7),"",true)
call TriggerAddCondition(gg_trg_qqqq,Condition(function Trig_qqqq_Conditions))
call TriggerAddAction(gg_trg_qqqq,function Trig_qqqq_Actions)