set gg_trg_CreateItem=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(0),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(1),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(2),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(3),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(4),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(5),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(7),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(8),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(6),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(9),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(10),"",false)
call TriggerRegisterPlayerChatEvent(gg_trg_CreateItem,Player(11),"",false)
call TriggerAddAction(gg_trg_CreateItem,function Trig_CreateItem_Actions)