set gg_trg_lfhuiyuanaijingyanlv=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(0),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(1),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(2),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(3),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(4),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(5),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(6),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(7),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(8),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(9),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(10),"jingyan",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfhuiyuanaijingyanlv,Player(11),"jingyan",false)
call TriggerAddAction(gg_trg_lfhuiyuanaijingyanlv,function Trig_lfhuiyuanaijingyanlv_Actions)