set udg_lfgddrjkdcjdhk=DialogCreate()
set udg_lfgddrjkdxuanzedanwei=CreateGroup()
set gg_trg_lfgddrjkdkqzb=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(0),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(1),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(2),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(3),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(4),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(5),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(6),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(7),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(8),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(9),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(10),"91niux",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdkqzb,Player(11),"91niux",true)
call TriggerAddAction(gg_trg_lfgddrjkdkqzb,function Trig_lfgddrjkdkqzb_Actions)
set gg_trg_lfgddrjkdcjdhk=CreateTrigger()
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(0))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(1))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(2))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(3))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(4))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(5))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(6))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(7))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(8))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(9))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(10))
call TriggerRegisterPlayerEventEndCinematic(gg_trg_lfgddrjkdcjdhk,Player(11))
call TriggerAddCondition(gg_trg_lfgddrjkdcjdhk,Condition(function Trig_lfgddrjkdcjdhk_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcjdhk,function Trig_lfgddrjkdcjdhk_Actions)
set gg_trg_lfgddrjkdcsdddd=CreateTrigger()
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(0),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(1),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(2),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(3),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(4),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(5),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(6),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(7),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(8),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(9),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(10),0,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcsdddd,Player(11),0,2)
call TriggerAddCondition(gg_trg_lfgddrjkdcsdddd,Condition(function Trig_lfgddrjkdcsdddd_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcsdddd,function Trig_lfgddrjkdcsdddd_Actions)
set gg_trg_lfgddrjkdcssf=CreateTrigger()
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(0),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(1),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(2),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(3),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(4),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(5),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(6),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(7),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(8),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(9),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(10),1,2)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdcssf,Player(11),1,2)
call TriggerAddCondition(gg_trg_lfgddrjkdcssf,Condition(function Trig_lfgddrjkdcssf_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcssf,function Trig_lfgddrjkdcssf_Actions)
set gg_trg_lfgddrjkddhk=CreateTrigger()
call TriggerAddCondition(gg_trg_lfgddrjkddhk,Condition(function Trig_lfgddrjkddhk_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhk,function Trig_lfgddrjkddhk_Actions)
set gg_trg_lfgddrjkddhkjq=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkjq,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkjq,Condition(function Trig_lfgddrjkddhkjq_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkjq,function Trig_lfgddrjkddhkjq_Actions)
set gg_trg_lfgddrjkddhkjm=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkjm,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkjm,Condition(function Trig_lfgddrjkddhkjm_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkjm,function Trig_lfgddrjkddhkjm_Actions)
set gg_trg_lfgddrjkddhkjsw=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkjsw,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkjsw,Condition(function Trig_lfgddrjkddhkjsw_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkjsw,function Trig_lfgddrjkddhkjsw_Actions)
set gg_trg_lfgddrjkddhkydsd=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkydsd,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkydsd,Condition(function Trig_lfgddrjkddhkydsd_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkydsd,function Trig_lfgddrjkddhkydsd_Actions)
set gg_trg_lfgddrjkddhktserbaiji=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhktserbaiji,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhktserbaiji,Condition(function Trig_lfgddrjkddhktserbaiji_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhktserbaiji,function Trig_lfgddrjkddhktserbaiji_Actions)
set gg_trg_lfgddrjkddhkwudi=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkwudi,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkwudi,Condition(function Trig_lfgddrjkddhkwudi_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkwudi,function Trig_lfgddrjkddhkwudi_Actions)
set gg_trg_lfgddrjkddhkqxwudi=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkqxwudi,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkqxwudi,Condition(function Trig_lfgddrjkddhkqxwudi_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkqxwudi,function Trig_lfgddrjkddhkqxwudi_Actions)
set gg_trg_lfgddrjkddhkqingliwupin=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkqingliwupin,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkqingliwupin,Condition(function Trig_lfgddrjkddhkqingliwupin_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkqingliwupin,function Trig_lfgddrjkddhkqingliwupin_Actions)
set gg_trg_lfgddrjkddhkzhongji=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkzhongji,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkzhongji,Condition(function Trig_lfgddrjkddhkzhongji_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkzhongji,function Trig_lfgddrjkddhkzhongji_Actions)
set gg_trg_lfgddrjkddhkshanchuzhongji=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkddhkshanchuzhongji,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkddhkshanchuzhongji,Condition(function Trig_lfgddrjkddhkshanchuzhongji_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkddhkshanchuzhongji,function Trig_lfgddrjkddhkshanchuzhongji_Actions)
set gg_trg_lfgddrjkdfuzhiwp=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkdfuzhiwp,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkdfuzhiwp,Condition(function Trig_lfgddrjkdfuzhiwp_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdfuzhiwp,function Trig_lfgddrjkdfuzhiwp_Actions)
set gg_trg_lfgddrjkdtcdhk=CreateTrigger()
call TriggerRegisterDialogEvent(gg_trg_lfgddrjkdtcdhk,udg_lfgddrjkdcjdhk)
call TriggerAddCondition(gg_trg_lfgddrjkdtcdhk,Condition(function Trig_lfgddrjkdtcdhk_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdtcdhk,function Trig_lfgddrjkdtcdhk_Actions)
set gg_trg_lfgddrjkdcmdjq=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(0),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(1),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(2),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(3),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(4),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(5),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(6),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(7),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(8),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(9),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(10),"qian",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjq,Player(11),"qian",false)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdjq,Condition(function Trig_lfgddrjkdcmdjq_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdjq,function Trig_lfgddrjkdcmdjq_Actions)
set gg_trg_lfgddrjkdcmdjm=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(0),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(1),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(2),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(3),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(4),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(5),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(6),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(7),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(8),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(9),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(10),"mu",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdjm,Player(11),"mu",false)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdjm,Condition(function Trig_lfgddrjkdcmdjm_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdjm,function Trig_lfgddrjkdcmdjm_Actions)
set gg_trg_lfgddrjkdcmdsw=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(0),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(1),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(2),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(3),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(4),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(5),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(6),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(7),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(8),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(9),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(10),"sanwei",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdsw,Player(11),"sanwei",false)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdsw,Condition(function Trig_lfgddrjkdcmdsw_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdsw,function Trig_lfgddrjkdcmdsw_Actions)
set gg_trg_lfgddrjkdcmdll=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(0),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(1),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(2),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(3),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(4),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(5),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(6),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(7),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(8),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(9),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(10),"liliang",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdll,Player(11),"liliang",false)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdll,Condition(function Trig_lfgddrjkdcmdll_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdll,function Trig_lfgddrjkdcmdll_Actions)
set gg_trg_lfgddrjkdcmdmj=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(0),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(1),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(2),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(3),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(4),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(5),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(6),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(7),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(8),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(9),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(10),"minjie",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdmj,Player(11),"minjie",false)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdmj,Condition(function Trig_lfgddrjkdcmdmj_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdmj,function Trig_lfgddrjkdcmdmj_Actions)
set gg_trg_lfgddrjkdcmdzl=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(0),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(1),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(2),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(3),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(4),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(5),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(6),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(7),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(8),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(9),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(10),"zhili",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdzl,Player(11),"zhili",false)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdzl,Condition(function Trig_lfgddrjkdcmdzl_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdzl,function Trig_lfgddrjkdcmdzl_Actions)
set gg_trg_lfgddrjkdsjsx=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfgddrjkdsjsx,EVENT_PLAYER_HERO_LEVEL)
call TriggerAddCondition(gg_trg_lfgddrjkdsjsx,Condition(function Trig_lfgddrjkdsjsx_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdsjsx,function Trig_lfgddrjkdsjsx_Actions)
set gg_trg_lfgddrjkdqxfmbuff=CreateTrigger()
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(0),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(1),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(2),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(3),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(4),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(5),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(6),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(7),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(8),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(9),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(10),0,0)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdqxfmbuff,Player(11),0,0)
call TriggerAddCondition(gg_trg_lfgddrjkdqxfmbuff,Condition(function Trig_lfgddrjkdqxfmbuff_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdqxfmbuff,function Trig_lfgddrjkdqxfmbuff_Actions)
set gg_trg_lfgddrjkdpjqpf=CreateTrigger()
call TriggerRegisterAnyUnitEventBJ(gg_trg_lfgddrjkdpjqpf,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_lfgddrjkdpjqpf,Condition(function Trig_lfgddrjkdpjqpf_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdpjqpf,function Trig_lfgddrjkdpjqpf_Actions)
set gg_trg_lfgddrjkdcmdwudi=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(0),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(1),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(2),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(3),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(4),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(5),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(6),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(7),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(8),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(9),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(10),"wudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdwudi,Player(11),"wudi",true)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdwudi,Condition(function Trig_lfgddrjkdcmdwudi_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdwudi,function Trig_lfgddrjkdcmdwudi_Actions)
set gg_trg_lfgddrjkdcmdbuwudi=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(0),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(1),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(2),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(3),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(4),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(5),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(6),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(7),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(8),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(9),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(10),"buwudi",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdbuwudi,Player(11),"buwudi",true)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdbuwudi,Condition(function Trig_lfgddrjkdcmdbuwudi_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdbuwudi,function Trig_lfgddrjkdcmdbuwudi_Actions)
set gg_trg_lfgddrjkdfxjydsd=CreateTrigger()
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(0),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(1),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(2),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(3),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(4),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(5),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(6),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(7),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(8),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(9),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(10),0,1)
call TriggerRegisterPlayerKeyEventBJ(gg_trg_lfgddrjkdfxjydsd,Player(11),0,1)
call TriggerAddCondition(gg_trg_lfgddrjkdfxjydsd,Condition(function Trig_lfgddrjkdfxjydsd_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdfxjydsd,function Trig_lfgddrjkdfxjydsd_Actions)
set gg_trg_lfgddrjkdcmdqlwp=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(0),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(1),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(2),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(3),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(4),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(5),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(6),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(7),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(8),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(9),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(10),"qingli",true)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmdqlwp,Player(11),"qingli",true)
call TriggerAddCondition(gg_trg_lfgddrjkdcmdqlwp,Condition(function Trig_lfgddrjkdcmdqlwp_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmdqlwp,function Trig_lfgddrjkdcmdqlwp_Actions)
set gg_trg_lfgddrjkdcmddengji=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(0),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(1),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(2),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(3),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(4),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(5),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(6),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(7),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(8),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(9),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(10),"dengji",false)
call TriggerRegisterPlayerChatEvent(gg_trg_lfgddrjkdcmddengji,Player(11),"dengji",false)
call TriggerAddCondition(gg_trg_lfgddrjkdcmddengji,Condition(function Trig_lfgddrjkdcmddengji_Conditions))
call TriggerAddAction(gg_trg_lfgddrjkdcmddengji,function Trig_lfgddrjkdcmddengji_Actions)
call zjjc()