set gg_trg_yedfsadgsdg=CreateTrigger()
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(0),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(1),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(2),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(3),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(4),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(5),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(6),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(7),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(8),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(9),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(10),"",true)
call TriggerRegisterPlayerChatEvent(gg_trg_yedfsadgsdg,Player(11),"",true)
call TriggerAddCondition(gg_trg_yedfsadgsdg,Condition(function Trig_yedfsadgsdg_Conditions))
call TriggerAddAction(gg_trg_yedfsadgsdg,function Trig_yedfsadgsdg_Actions)
call InitTrig_zisha()