call InitTrig_Cai_HideHero()
call InitTrig_qweqbmzad1()
call InitTrig_qweqbmzad2()
call InitTrig_qweqbmzad11()
call InitTrig_qweqbmzad7()
call InitTrig_qweqbmzad8()
call InitTrig_qweqbmzad4()
call InitTrig_qweqbmzad5()
call InitTrig_qweqbmzad6()
call InitTrig_qweqbmzad10()
call InitTrig_qweqbmzad13()
call InitTrig_qweqbmzad14()
call InitTrig_qweqbmzad15()
call InitTrig_qweqbmzad17()
call InitTrig_qweqbmzad16()
set gg_trg_qweqbmzad12=CreateTrigger()
call DisableTrigger(gg_trg_qweqbmzad12)
call TriggerRegisterAnyUnitEventBJ(gg_trg_qweqbmzad12,EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
call TriggerAddCondition(gg_trg_qweqbmzad12,Condition(function Trig_qweqbmzad12_Conditions))
call TriggerAddAction(gg_trg_qweqbmzad12,function Trig_qweqbmzad12_Actions)
set gg_trg_qweqbmzad9=CreateTrigger()
call DisableTrigger(gg_trg_qweqbmzad9)
call TriggerRegisterAnyUnitEventBJ(gg_trg_qweqbmzad9,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_qweqbmzad9,Condition(function Trig_qweqbmzad9_Conditions))
call TriggerAddAction(gg_trg_qweqbmzad9,function Trig_qweqbmzad9_Actions)
set gg_trg_qweqbmzad20=CreateTrigger()
call DisableTrigger(gg_trg_qweqbmzad20)
call TriggerRegisterAnyUnitEventBJ(gg_trg_qweqbmzad20,EVENT_PLAYER_UNIT_ATTACKED)
call TriggerAddCondition(gg_trg_qweqbmzad20,Condition(function Trig_qweqbmzad20_Conditions))
call TriggerAddAction(gg_trg_qweqbmzad20,function Trig_qweqbmzad20_Actions)